from music21 import *
c = clef.SopranoClef()
ts = meter.TimeSignature('4/4')
ks = key.KeySignature(-3)
puzzle1 = stream.Stream(cautionaryAll=True, cautionaryPitchClass=True, cautionaryNotImmediateRepeat =True)
puzzle1.insert(0.0, c)
puzzle1.insert(0.0, ts)
puzzle1.insert(0.0, ks)

puzzle1.append(note.Note('C4', quarterLength=2))
puzzle1.append(note.Note('E-4', quarterLength=2))

puzzle1.append(note.Note('G4', quarterLength=2))
puzzle1.append(note.Note('A-4', quarterLength=2))

puzzle1.append(note.Note('B3', quarterLength=2))
puzzle1.append(note.Rest())
puzzle1.append(note.Note('G4', quarterLength=2))
puzzle1.append(note.Note('F#4', quarterLength=2))
puzzle1.append(note.Note('F4', quarterLength=2))
puzzle1.append(note.Note('E4', quarterLength=2))
puzzle1.append(note.Note('E-4', quarterLength=2))

puzzle1.append(note.Note('D4', quarterLength=1))
puzzle1.append(note.Note('D-4', quarterLength=1))
puzzle1.append(note.Note('C4', quarterLength=1))

puzzle1.append(note.Note('B3', quarterLength=1))
puzzle1.append(note.Note('G3', quarterLength=1))
puzzle1.append(note.Note('C4', quarterLength=1))
puzzle1.append(note.Note('F4', quarterLength=1))

puzzle1.append(note.Note('E-4', quarterLength=2))
puzzle1.append(note.Note('D4', quarterLength=2))

puzzle1.append(note.Note('C4', quarterLength=2))
puzzle1.append(note.Note('E-4', quarterLength=2))

puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('E-4', quarterLength=0.5))
puzzle1.append(note.Note('D4', quarterLength=0.5))
puzzle1.append(note.Note('E-4', quarterLength=0.5))

puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('A4', quarterLength=0.5))
puzzle1.append(note.Note('B4', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('E-4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))

puzzle1.append(note.Note('A-4', quarterLength=0.5))
puzzle1.append(note.Note('D4', quarterLength=0.5))
puzzle1.append(note.Note('E-4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('E-4', quarterLength=0.5))
puzzle1.append(note.Note('D4', quarterLength=0.5))

puzzle1.append(note.Note('E-4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('A-4', quarterLength=0.5))
puzzle1.append(note.Note('B-4', quarterLength=0.5))
puzzle1.append(note.Note('A-4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('F4', quarterLength=0.5))

puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('A-4', quarterLength=0.5))
puzzle1.append(note.Note('B-4', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('D-5', quarterLength=0.5))
puzzle1.append(note.Note('B-4', quarterLength=0.5))
puzzle1.append(note.Note('A-4', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))

puzzle1.append(note.Note('A4', quarterLength=0.5))
puzzle1.append(note.Note('B4', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))
puzzle1.append(note.Note('E-5', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('B4', quarterLength=0.5))
puzzle1.append(note.Note('A4', quarterLength=0.5))

puzzle1.append(note.Note('B4', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))
puzzle1.append(note.Note('E-5', quarterLength=0.5))
puzzle1.append(note.Note('F5', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))
puzzle1.append(note.Note('G4', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))

puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))
puzzle1.append(note.Note('E-5', quarterLength=0.5))
puzzle1.append(note.Note('F5', quarterLength=0.5))
puzzle1.append(note.Note('E-5', quarterLength=0.5))
puzzle1.append(note.Note('D5', quarterLength=0.5))
puzzle1.append(note.Note('C5', quarterLength=0.5))
puzzle1.append(note.Note('B4', quarterLength=0.5))

puzzle1.append(note.Note('C5', quarterLength=1))
puzzle1.append(note.Note('G4', quarterLength=1))
puzzle1.append(note.Note('E-4', quarterLength=1))
puzzle1.append(note.Note('C4', quarterLength=1))


puzzle1.show()

